package com.APIMM.etmain.model;
// Generated Jan 4, 2018 4:39:46 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SettingsId generated by hbm2java
 */
@Entity
@Table(name = "Settings")
public class Setting implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String name;
	private String value;

	public Setting() {
	}

	public Setting(String name, String value) {
		this.name = name;
		this.value = value;
	}
	
	@Id
	@GeneratedValue
	@Column(name = "Name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", length = 200)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Setting))
			return false;
		Setting castOther = (Setting) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
				&& this.getName().equals(castOther.getName())))
				&& ((this.getValue() == castOther.getValue()) || (this.getValue() != null
						&& castOther.getValue() != null && this.getValue().equals(castOther.getValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getValue() == null ? 0 : this.getValue().hashCode());
		return result;
	}

}
