package com.APIMM.etmain.model;
// Generated Jan 4, 2018 3:51:19 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentTagIdmappings generated by hbm2java
 */
@Entity
@Table(name = "StudentTagIDMappings")
public class StudentTagIdmappings implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private String edulogStudentId;
	private String tagId;
	private Date effectiveDate;
	private Date endDate;
	private Date recordCreatedTime;
	private String tagType;
	private String districtId;

	public StudentTagIdmappings() {
	}

	public StudentTagIdmappings(String edulogStudentId) {
		this.edulogStudentId = edulogStudentId;
	}

	public StudentTagIdmappings(String edulogStudentId, String tagId, Date effectiveDate, Date endDate,
			Date recordCreatedTime, String tagType, String districtId) {
		this.edulogStudentId = edulogStudentId;
		this.tagId = tagId;
		this.effectiveDate = effectiveDate;
		this.endDate = endDate;
		this.recordCreatedTime = recordCreatedTime;
		this.tagType = tagType;
		this.districtId = districtId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "EdulogStudentID", nullable = false, length = 50)
	public String getEdulogStudentId() {
		return this.edulogStudentId;
	}

	public void setEdulogStudentId(String edulogStudentId) {
		this.edulogStudentId = edulogStudentId;
	}

	@Column(name = "TagID", length = 50)
	public String getTagId() {
		return this.tagId;
	}

	public void setTagId(String tagId) {
		this.tagId = tagId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EffectiveDate", length = 23)
	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RecordCreatedTime", length = 23)
	public Date getRecordCreatedTime() {
		return this.recordCreatedTime;
	}

	public void setRecordCreatedTime(Date recordCreatedTime) {
		this.recordCreatedTime = recordCreatedTime;
	}

	@Column(name = "TagType")
	public String getTagType() {
		return this.tagType;
	}

	public void setTagType(String tagType) {
		this.tagType = tagType;
	}

	@Column(name = "DistrictID", length = 32)
	public String getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(String districtId) {
		this.districtId = districtId;
	}

}
