package com.APIMM.etmain.model;
// Generated Jan 3, 2018 5:07:05 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VehicleGpsunitMappingsId generated by hbm2java
 */
@Entity
@Table(name = "VehicleGPSUnitMappings")
public class VehicleGpsunitMappings implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String unitId;
	private String busNumber;
	private Date installDate;
	private Date effectiveDate;
	private Date endDate;
	private Date recordCreatedTime;
	private String comments;
	private Integer active;
	private Integer spare;
	private String unitType;
	private String vehicleType;
	private Integer repair;
	private long id;
	private Boolean daisyChain;
	private Boolean mdtRegularEd;
	private Boolean edta;
	private String assetId;

	public VehicleGpsunitMappings() {
	}

	public VehicleGpsunitMappings(String unitId, long id) {
		this.unitId = unitId;
		this.id = id;
	}

	public VehicleGpsunitMappings(String unitId, String busNumber, Date installDate, Date effectiveDate, Date endDate,
			Date recordCreatedTime, String comments, Integer active, Integer spare, String unitType, String vehicleType,
			Integer repair, long id, Boolean daisyChain, Boolean mdtRegularEd, Boolean edta, String assetId) {
		this.unitId = unitId;
		this.busNumber = busNumber;
		this.installDate = installDate;
		this.effectiveDate = effectiveDate;
		this.endDate = endDate;
		this.recordCreatedTime = recordCreatedTime;
		this.comments = comments;
		this.active = active;
		this.spare = spare;
		this.unitType = unitType;
		this.vehicleType = vehicleType;
		this.repair = repair;
		this.id = id;
		this.daisyChain = daisyChain;
		this.mdtRegularEd = mdtRegularEd;
		this.edta = edta;
		this.assetId = assetId;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "UnitID", nullable = false, length = 50)
	public String getUnitId() {
		return this.unitId;
	}

	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}

	@Column(name = "BusNumber", length = 50)
	public String getBusNumber() {
		return this.busNumber;
	}

	public void setBusNumber(String busNumber) {
		this.busNumber = busNumber;
	}

	@Column(name = "InstallDate", length = 23)
	public Date getInstallDate() {
		return this.installDate;
	}

	public void setInstallDate(Date installDate) {
		this.installDate = installDate;
	}

	@Column(name = "EffectiveDate", length = 23)
	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	@Column(name = "EndDate", length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "RecordCreatedTime", length = 23)
	public Date getRecordCreatedTime() {
		return this.recordCreatedTime;
	}

	public void setRecordCreatedTime(Date recordCreatedTime) {
		this.recordCreatedTime = recordCreatedTime;
	}

	@Column(name = "Comments", length = 200)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "Active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@Column(name = "Spare")
	public Integer getSpare() {
		return this.spare;
	}

	public void setSpare(Integer spare) {
		this.spare = spare;
	}

	@Column(name = "UnitType", length = 50)
	public String getUnitType() {
		return this.unitType;
	}

	public void setUnitType(String unitType) {
		this.unitType = unitType;
	}

	@Column(name = "VehicleType", length = 50)
	public String getVehicleType() {
		return this.vehicleType;
	}

	public void setVehicleType(String vehicleType) {
		this.vehicleType = vehicleType;
	}

	@Column(name = "Repair")
	public Integer getRepair() {
		return this.repair;
	}

	public void setRepair(Integer repair) {
		this.repair = repair;
	}

	@Column(name = "ID", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "daisy_chain")
	public Boolean getDaisyChain() {
		return this.daisyChain;
	}

	public void setDaisyChain(Boolean daisyChain) {
		this.daisyChain = daisyChain;
	}

	@Column(name = "MDT_regular_ed")
	public Boolean getMdtRegularEd() {
		return this.mdtRegularEd;
	}

	public void setMdtRegularEd(Boolean mdtRegularEd) {
		this.mdtRegularEd = mdtRegularEd;
	}

	@Column(name = "eDTA")
	public Boolean getEdta() {
		return this.edta;
	}

	public void setEdta(Boolean edta) {
		this.edta = edta;
	}

	@Column(name = "AssetID", length = 50)
	public String getAssetId() {
		return this.assetId;
	}

	public void setAssetId(String assetId) {
		this.assetId = assetId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VehicleGpsunitMappings))
			return false;
		VehicleGpsunitMappings castOther = (VehicleGpsunitMappings) other;

		return ((this.getUnitId() == castOther.getUnitId()) || (this.getUnitId() != null
				&& castOther.getUnitId() != null && this.getUnitId().equals(castOther.getUnitId())))
				&& ((this.getBusNumber() == castOther.getBusNumber()) || (this.getBusNumber() != null
						&& castOther.getBusNumber() != null && this.getBusNumber().equals(castOther.getBusNumber())))
				&& ((this.getInstallDate() == castOther.getInstallDate())
						|| (this.getInstallDate() != null && castOther.getInstallDate() != null
								&& this.getInstallDate().equals(castOther.getInstallDate())))
				&& ((this.getEffectiveDate() == castOther.getEffectiveDate())
						|| (this.getEffectiveDate() != null && castOther.getEffectiveDate() != null
								&& this.getEffectiveDate().equals(castOther.getEffectiveDate())))
				&& ((this.getEndDate() == castOther.getEndDate()) || (this.getEndDate() != null
						&& castOther.getEndDate() != null && this.getEndDate().equals(castOther.getEndDate())))
				&& ((this.getRecordCreatedTime() == castOther.getRecordCreatedTime())
						|| (this.getRecordCreatedTime() != null && castOther.getRecordCreatedTime() != null
								&& this.getRecordCreatedTime().equals(castOther.getRecordCreatedTime())))
				&& ((this.getComments() == castOther.getComments()) || (this.getComments() != null
						&& castOther.getComments() != null && this.getComments().equals(castOther.getComments())))
				&& ((this.getActive() == castOther.getActive()) || (this.getActive() != null
						&& castOther.getActive() != null && this.getActive().equals(castOther.getActive())))
				&& ((this.getSpare() == castOther.getSpare()) || (this.getSpare() != null
						&& castOther.getSpare() != null && this.getSpare().equals(castOther.getSpare())))
				&& ((this.getUnitType() == castOther.getUnitType()) || (this.getUnitType() != null
						&& castOther.getUnitType() != null && this.getUnitType().equals(castOther.getUnitType())))
				&& ((this.getVehicleType() == castOther.getVehicleType())
						|| (this.getVehicleType() != null && castOther.getVehicleType() != null
								&& this.getVehicleType().equals(castOther.getVehicleType())))
				&& ((this.getRepair() == castOther.getRepair()) || (this.getRepair() != null
						&& castOther.getRepair() != null && this.getRepair().equals(castOther.getRepair())))
				&& (this.getId() == castOther.getId())
				&& ((this.getDaisyChain() == castOther.getDaisyChain()) || (this.getDaisyChain() != null
						&& castOther.getDaisyChain() != null && this.getDaisyChain().equals(castOther.getDaisyChain())))
				&& ((this.getMdtRegularEd() == castOther.getMdtRegularEd())
						|| (this.getMdtRegularEd() != null && castOther.getMdtRegularEd() != null
								&& this.getMdtRegularEd().equals(castOther.getMdtRegularEd())))
				&& ((this.getEdta() == castOther.getEdta()) || (this.getEdta() != null && castOther.getEdta() != null
						&& this.getEdta().equals(castOther.getEdta())))
				&& ((this.getAssetId() == castOther.getAssetId()) || (this.getAssetId() != null
						&& castOther.getAssetId() != null && this.getAssetId().equals(castOther.getAssetId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUnitId() == null ? 0 : this.getUnitId().hashCode());
		result = 37 * result + (getBusNumber() == null ? 0 : this.getBusNumber().hashCode());
		result = 37 * result + (getInstallDate() == null ? 0 : this.getInstallDate().hashCode());
		result = 37 * result + (getEffectiveDate() == null ? 0 : this.getEffectiveDate().hashCode());
		result = 37 * result + (getEndDate() == null ? 0 : this.getEndDate().hashCode());
		result = 37 * result + (getRecordCreatedTime() == null ? 0 : this.getRecordCreatedTime().hashCode());
		result = 37 * result + (getComments() == null ? 0 : this.getComments().hashCode());
		result = 37 * result + (getActive() == null ? 0 : this.getActive().hashCode());
		result = 37 * result + (getSpare() == null ? 0 : this.getSpare().hashCode());
		result = 37 * result + (getUnitType() == null ? 0 : this.getUnitType().hashCode());
		result = 37 * result + (getVehicleType() == null ? 0 : this.getVehicleType().hashCode());
		result = 37 * result + (getRepair() == null ? 0 : this.getRepair().hashCode());
		result = 37 * result + (int) this.getId();
		result = 37 * result + (getDaisyChain() == null ? 0 : this.getDaisyChain().hashCode());
		result = 37 * result + (getMdtRegularEd() == null ? 0 : this.getMdtRegularEd().hashCode());
		result = 37 * result + (getEdta() == null ? 0 : this.getEdta().hashCode());
		result = 37 * result + (getAssetId() == null ? 0 : this.getAssetId().hashCode());
		return result;
	}

}
