package com.APIMM.mam.model;
// Generated Nov 13, 2017 11:32:06 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MamDeviceEvent generated by hbm2java
 */
@Entity
@Table(name = "DP_Routes")
public class DPRoutes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer routeId;
	private String routeNumber;
	private Integer dev_Id;
	private String routeDesc;
	private Date routeDate;	
	private Date lastUpdated;
	
	private List<DPRuns> runs;
	public DPRoutes() {
	}

	public DPRoutes(Integer routeId, String routeNumber, Integer dev_Id, String routeDesc, Date routeDate,
			Date lastUpdated, List<DPRuns> runs) {
		super();
		this.routeId = routeId;
		this.routeNumber = routeNumber;
		this.dev_Id = dev_Id;
		this.routeDesc = routeDesc;
		this.routeDate = routeDate;
		this.lastUpdated = lastUpdated;
		this.runs = runs;
	}

	@OneToMany(fetch = FetchType.LAZY, cascade = { CascadeType.ALL,CascadeType.PERSIST,CascadeType.MERGE }, mappedBy = "routes", orphanRemoval=true)
    @Column(nullable = false)
    public List<DPRuns> getruns () { return runs; }
    public void setruns( List<DPRuns> eRuns) { this.runs = eRuns; }    
    
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "routeId", unique = true, nullable = false)
	public Integer getrouteId() {
		return this.routeId;
	}

	public void setrouteId(Integer routeId) {
		this.routeId = routeId;
	}

	@Column(name = "routeNumber")
	public String getrouteNumber() {
		return this.routeNumber;
	}

	public void setrouteNumber(String routeNumber) {
		this.routeNumber = routeNumber;
	}
	
	
			
	@Column(name = "dev_Id")	
	public Integer getdev_Id() {
		return this.dev_Id;
	}

	public void setdev_Id(Integer dev_Id) {
		this.dev_Id = dev_Id;
	}

	@Column(name = "routeDesc")
	public String getrouteDesc() {
		return this.routeDesc;
	}

	public void setrouteDesc(String routeDesc) {
		this.routeDesc = routeDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern="yyyy-MM-dd")		
	@Column(name = "routeDate", length = 23)
	public Date getrouteDate() {
		return this.routeDate;
	}

	public void setrouteDate(Date routeDate) {
		this.routeDate = routeDate;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@JsonIgnore	
	@Column(name = "lastUpdated", length = 23)
	public Date getLastUpdated() {
		return lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}
}
