package com.APIMM.mam.model;
// Generated Nov 13, 2017 11:32:06 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MamDeviceEvent generated by hbm2java
 */
@Entity
@Table(name = "DP_RunDirs")
public class DPRunDirs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;		
	
	private Integer runDirsId;
	private Integer runRoute;
	private Integer devId;
	private String busNumber;
	private Integer sequence;
	private Date time;
	private Double latitude;
	private Double longitude;
	private Date lastUpdated;
	public DPRunDirs() {
	}

	public DPRunDirs(Integer runDirsId,Integer runRoute,Integer sequence, Double latitude,Double longitude, Date lastUpdated) {
		super();
		this.runDirsId = runDirsId;
		this.runRoute = runRoute;
		this.sequence = sequence;
		this.latitude = latitude;		
		this.longitude = longitude;
		this.lastUpdated = lastUpdated;		
	}

	    
    
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "runDirsId", unique = true, nullable = false)
	public Integer getrunDirsId() {
		return this.runDirsId;
	}

	public void setrunDirsId(Integer runDirsId) {
		this.runDirsId = runDirsId;
	}
	
	@Column(name = "runRoute")
	public Integer getrunRoute() {
		return this.runRoute;
	}

	public void setrunRoute(Integer runRoute) {
		this.runRoute = runRoute;
	}
	
	@Column(name = "sequence")
	public Integer getsequence() {
		return this.sequence;
	}

	public void setsequence(Integer sequence) {
		this.sequence = sequence;
	}

	@Column(name = "latitude")
	public Double getlatitude() {
		return this.latitude;
	}

	public void setlatitude(Double latitude) {
		this.latitude = latitude;
	}
	
	@Column(name = "longitude")
	public Double getlongitude() {
		return this.longitude;
	}

	public void setlongitude(Double longitude) {
		this.longitude = longitude;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@JsonIgnore	
	@Column(name = "lastUpdated", length = 23)
	public Date getLastUpdated() {
		return lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}
	@Column(name = "bus_id")
	public String getbusNumber() {
		return this.busNumber;
	}

	public void setbusNumber(String busNumber) {
		this.busNumber = busNumber;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss.SSS")
	@Column(name = "tstamp", length = 23)
	public Date gettime() {
		return this.time;
	}

	public void settime(Date time) {
		this.time = time;
	}
	@Column(name = "dev_id")
	public Integer getdevId() {
		return this.devId;
	}

	public void setdevId(Integer devId) {
		this.devId = devId;
	}
}
