package com.APIMM.mam.model;
// Generated Nov 13, 2017 11:32:06 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MamDeviceEvent generated by hbm2java
 */
@Entity
@Table(name = "DP_Stops")
public class DPStops2 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer stopRunId;
	private String stopId;
	private Integer runRoute;
	private String location;
	private Double latitude;
	private Double longitude;
	private Integer numberOfStudents;
	private String stopDesc;
	private Date stopTime;	
	private DPRuns2 runs;
	private Date lastUpdated;
	public DPStops2() {
	}

	public DPStops2(Integer stopRunId, String stopId, Integer runRoute, String location, Double latitude,
			Double longitude, Integer numberOfStudents, String stopDesc, Date stopTime, DPRuns2 runs, Date lastUpdated) {
		super();
		this.stopRunId = stopRunId;
		this.stopId = stopId;
		this.runRoute = runRoute;
		this.location = location;
		this.latitude = latitude;
		this.longitude = longitude;
		this.numberOfStudents = numberOfStudents;
		this.stopDesc = stopDesc;
		this.stopTime = stopTime;
		this.runs = runs;
		this.lastUpdated = lastUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "stopRunId", unique = true, nullable = false)
	public Integer getstopRunId() {
		return this.stopRunId;
	}

	public void setstopRunId(Integer stopRunId) {
		this.stopRunId = stopRunId;
	}

	@Column(name = "stopId")
	public String getstopId() {
		return this.stopId;
	}

	public void setstopId(String stopId) {
		this.stopId = stopId;
	}
	@ManyToOne( fetch = FetchType.EAGER )
	@JsonIgnore
	@JoinColumn(name = "runRoute", nullable = false )
	public DPRuns2 getruns() { return runs; }
	public void setruns(DPRuns2 runs) {
		this.runs = runs;
	}
	   
//	@Column(name = "runRoute")
//	@JsonIgnore
//	public Integer getrunRoute() {
//		return this.runRoute;
//	}
//
//	public void setrunRoute() {
//		this.runRoute = runs.getrunRoute();
//	}
	
	@Column(name = "location")
	public String getlocation() {
		return this.location;
	}

	public void setlocation(String location) {
		this.location = location;
	}
	
	@Column(name = "latitude", precision = 53, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 53, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}
		
	@Column(name = "numberOfStudents")	
	public Integer getnumberOfStudents() {
		return this.numberOfStudents;
	}

	public void setnumberOfStudents(Integer numberOfStudents) {
		this.numberOfStudents = numberOfStudents;
	}

	@Column(name = "stopDesc")
	public String getstopDesc() {
		return this.stopDesc;
	}

	public void setstopDesc(String stopDesc) {
		this.stopDesc = stopDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss.SSS")		
	@Column(name = "stoptime", length = 23)
	public Date getstopTime() {
		return this.stopTime;
	}

	public void setstopTime(Date stopTime) {
		this.stopTime = stopTime;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@JsonIgnore	
	@Column(name = "lastUpdated", length = 23)
	public Date getLastUpdated() {
		return lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}
}
