package com.APIMM.mam.model;
// Generated Sep 13, 2017 6:30:10 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * MamApplication generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Entity
@Table(name = "mam_application")
public class MamApplication implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer appID;
	private String appName;
	private String appVersion;
	private Set<MamModule> mamModuleses = new HashSet<MamModule>(0);

	public MamApplication() {
	}

	public MamApplication(String appName, String appVersion, Set<MamModule> mamModuleses) {
		this.appName = appName;
		this.appVersion = appVersion;
		this.mamModuleses = mamModuleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@JsonIgnore
	@Column(name = "app_id", unique = true, nullable = false)
	public Integer getappID() {
		return this.appID;
	}

	public void setappID(Integer appID) {
		this.appID = appID;
	}

	@Column(name = "app_name")
	public String getAppName() {
		return this.appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	@Column(name = "app_version")
	public String getAppVersion() {
		return this.appVersion;
	}

	public void setAppVersion(String appVersion) {
		this.appVersion = appVersion;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "mamApplication")
	@JsonIgnore
	public Set<MamModule> getMamModuleses() {
		return this.mamModuleses;
	}

	public void setMamModuleses(Set<MamModule> mamModuleses) {
		this.mamModuleses = mamModuleses;
	}

}
