package com.APIMM.mam.model;
// Generated Sep 13, 2017 6:30:10 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MamDevModule generated by hbm2java
 */
@Entity
@Table(name = "MAM_Dev_Module")
public class MamDevModule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer devModuleId;
	private MamModule mamModules;
	private MdmDevice mdmDevices;	
	private String moduleName;
	private String moduleDescription;
	private Boolean devModuleEnable;
	private Boolean isDefault;
	private Date devModuleUpdated;	
	private Integer devId; 
	private Integer moduleId;
	
	
	public MamDevModule() {
	}

	public MamDevModule(Integer devModuleId, MamModule mamModules, MdmDevice mdmDevices) {
		this.devModuleId = devModuleId;
		this.mamModules = mamModules;
		this.mdmDevices = mdmDevices;
	}

	public MamDevModule(Integer devModuleId, MamModule mamModules, MdmDevice mdmDevices, Boolean devModuleEnable, Boolean isDefault,
			Date devModuleUpdated) {
		this.devModuleId = devModuleId;
		this.mamModules = mamModules;
		this.mdmDevices = mdmDevices;
		this.devModuleEnable = devModuleEnable;
		this.isDefault = isDefault;
		this.devModuleUpdated = devModuleUpdated;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@JsonIgnore
	@Column(name = "dev_module_id", unique = true, nullable = false)
	public Integer getDevModuleId() {
		return this.devModuleId;
	}

	public void setDevModuleId(Integer devModuleId) {
		this.devModuleId = devModuleId;
	}
	@JsonIgnore
	@ManyToOne(cascade=CascadeType.MERGE, fetch=FetchType.EAGER)
	@JoinColumn(name = "module_id", nullable = false)
	public MamModule getMamModules() {
		return this.mamModules;
	}

	public void setMamModules(MamModule mamModules) {
		this.mamModules = mamModules;
	}
	@JsonIgnore
	@ManyToOne(cascade=CascadeType.MERGE, fetch=FetchType.EAGER)
	@JoinColumn(name = "dev_id", nullable = false)
	public MdmDevice getMdmDevices() {
		return this.mdmDevices;
	}

	public void setMdmDevices(MdmDevice mdmDevices) {
		this.mdmDevices = mdmDevices;
	}

	@Column(name = "dev_module_enable")
	public Boolean getDevModuleEnable() {
		return this.devModuleEnable;
	}

	public void setDevModuleEnable(Boolean devModuleEnable) {
		this.devModuleEnable = devModuleEnable;
	}
	@Column(name = "dev_module_default")	
	public Boolean getisDefault() {		
		return this.isDefault;
	}

	public void setisDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}
	@JsonIgnore
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dev_module_updated", length = 23)
	public Date getDevModuleUpdated() {
		return this.devModuleUpdated;
	}

	public void setDevModuleUpdated(Date devModuleUpdated) {
		this.devModuleUpdated = devModuleUpdated;
	}
	
	@Transient
	public String getmoduleName() {
		if (this.mamModules!=null){
			return this.mamModules.getModuleName();
		}
		return "";
	}

	public void setmoduleName(String modulename) {
		this.moduleName = modulename;
	}
	
	@Transient
	public String getmoduleDescription() {
		if (this.mamModules!=null){
			return this.mamModules.getModuleDescription();
		}
		return "";
	}

	public void setmoduleDescription(String moduledescription) {
		this.moduleDescription = moduledescription;
	}

	@JsonIgnore
	@Transient
	public Integer getDevId() {
		
		if(this.mdmDevices != null) {
			return this.mdmDevices.getdevID();
		}
		
		return null;
	}

	public void setDevId(Integer devId) {
		this.devId = devId;
	}
	
	@JsonIgnore
	@Transient
	public Integer getModuleId() {
		if (this.mamModules!=null){
			return this.mamModules.getModuleId();
		}
		return null;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}
	
	
	
}
