package com.APIMM.mam.model;
// Generated Sep 13, 2017 6:30:10 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MamDevModule generated by hbm2java
 */
@Entity
@Table(name = "MAM_Default_Module")
public class MamDefaultModule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer defaultModuleId;
	private Integer appId;
	private Integer moduleId;	
	private Date defaultModuleCreated;
	public MamDefaultModule() {
	}
	

	public MamDefaultModule(Integer defaultModuleId, Integer appId,Integer moduleId, Date defaultModuleCreated) {
		this.defaultModuleId = defaultModuleId;
		this.appId = appId;
		this.moduleId = moduleId;
		this.defaultModuleCreated = defaultModuleCreated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@JsonIgnore
	@Column(name = "default_module_id", unique = true, nullable = false)
	public Integer getDefaultModuleId() {
		return this.defaultModuleId;
	}

	public void setDefaultModuleId(Integer defaultModuleId) {
		this.defaultModuleId = defaultModuleId;
	}
	@Column(name = "app_id")
	public Integer getappId() {
		return this.appId;
	}

	public void setappId(Integer appId) {
		this.appId = appId;
	}
	
	@Column(name = "module_id")
	public Integer getmoduleId() {
		return this.moduleId;
	}

	public void setmoduleId(Integer moduleId) {
		this.moduleId = moduleId;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss.SSS")	
	@Column(name = "default_module_created", length = 23)
	public Date getDefaultModuleCreated() {
		return this.defaultModuleCreated;
	}

	public void setDefaultModuleCreated(Date defaultModuleCreated) {
		this.defaultModuleCreated = defaultModuleCreated;
	}	
		
}
