package com.APIMM.mam.model;
// Generated Sep 13, 2017 6:30:10 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MamApplication generated by hbm2java
 */
@Entity
@Table(name = "MAM_Dev_SyncInfo")
public class MamDevSyncInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer appID;
	private Integer devID;
	private Date syncDate;
	private Date updateTime;

	public MamDevSyncInfo() {
	}

	public MamDevSyncInfo(Integer appID, Integer devID,Date syncDate, Date updateTime) {
		this.appID = appID;
		this.devID = devID;
		this.syncDate = syncDate;	
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@JsonIgnore
	@Column(name = "id", unique = true, nullable = false)
	public Integer getid() {
		return this.id;
	}

	public void setid(Integer ID) {
		this.id = ID;
	}

	@Column(name = "app_id")
	public Integer getappID() {
		return this.appID;
	}

	public void setappID(Integer appID) {
		this.appID = appID;
	}

	@Column(name = "dev_id")
	public Integer getdevID() {
		return this.devID;
	}

	public void setdevID(Integer devID) {
		this.devID = devID;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sync_date", length = 23)
	public Date getsyncDate() {
		return this.syncDate;
	}

	public void setsyncDate(Date syncDate) {
		this.syncDate = syncDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "update_time", length = 23)
	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	
}
