package com.APIMM.mam.model;
// Generated Nov 13, 2017 11:32:06 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MamDeviceEvent generated by hbm2java
 */
@Entity
@Table(name = "MAM_Device_Event")
public class MamDeviceEvent implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer deviceEventId;
	private Integer devId;
	private String busId;
	private Double latitude;
	private Double longitude;
	private Date eventTime;
	private Date eventSend;
	private Date eventWriteTime;
	private Integer eventId;
	private String eventName;
	private String status;

	public MamDeviceEvent() {
	}

	public MamDeviceEvent(Integer devId, String busId, Double latitude, Double longitude, Date eventTime,
			Date eventSend, Date eventWriteTime, Integer eventId, String eventName, String status, String runId, String routeNumber
			 ) {
		this.devId = devId;
		this.busId = busId;
		this.latitude = latitude;
		this.longitude = longitude;
		this.eventTime = eventTime;
		this.eventSend = eventSend;
		this.eventWriteTime = eventWriteTime;
		this.eventId = eventId;
		this.eventName = eventName;
		this.status = status;	
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "device_event_id", unique = true, nullable = false)
	public Integer getDeviceEventId() {
		return this.deviceEventId;
	}

	public void setDeviceEventId(Integer deviceEventId) {
		this.deviceEventId = deviceEventId;
	}


	@Column(name = "dev_id")
	public Integer getDevId() {
		return this.devId;
	}

	public void setDevId(Integer devId) {
		this.devId = devId;
	}

	@Column(name = "bus_id")
	public String getBusId() {
		return this.busId;
	}

	public void setBusId(String busId) {
		this.busId = busId;
	}

	@Column(name = "latitude", precision = 53, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 53, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss.SSS")		
	@Column(name = "event_time", length = 23)
	public Date getEventTime() {
		return this.eventTime;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss.SSS")
	@Column(name = "event_send", length = 23)
	public Date getEventSend() {
		return this.eventSend;
	}

	public void setEventSend(Date eventSend) {
		this.eventSend = eventSend;
	}
	@Column(name = "event_write_tstamp",nullable= false)
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss.SSS")
	@JsonIgnore
	public Date geteventWriteTime() {		
		return eventWriteTime;
	}
	public void seteventWriteTime(Date eventWriteTime) {				
		this.eventWriteTime = eventWriteTime;
	}
	@Column(name = "event_id")
	@JsonIgnore
	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	@Column(name = "event_name")
	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	@Column(name = "status")
	public String getstatus() {
		return this.status;
	}

	public void setstatus(String status) {
		this.status = status;
	}

}
