package com.APIMM.mam.model;
// Generated Sep 13, 2017 6:30:10 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MamSettings generated by hbm2java
 */
@Entity
@Table(name = "DevMessage")
public class MamDeviceMessage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;	
	private Integer devId;
	private String moduleName;	
	private String functionName;
	private String message;
	private Date messageTime;
	private Date lastUpdated;
	
	public MamDeviceMessage() {
	}

	public MamDeviceMessage(Integer id) {
		this.id = id;
	}

	public MamDeviceMessage(Integer id, Integer devID, String moduleName, String functionName,String message, 
			Date messageTime, Date lastUpdated ) {
		this.id = id;
		this.devId = devID;
		this.moduleName = moduleName;
		this.functionName = functionName;
		this.message = message;
		this.messageTime = messageTime;
		this.lastUpdated = lastUpdated;
	
	}
	
	@JsonIgnore
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getid() {
		return this.id;
	}

	public void setid(Integer id) {
		this.id = id;
	}
	
	@Column(name = "dev_id")
	public Integer getdevId() {
		return this.devId;
	}
	public void setdevId(Integer devID) {
		this.devId = devID;
	}
	
	@Column(name = "modulename")
	public String getmoduleName() {
		return this.moduleName;
	}

	public void setmoduleName(String moduleName) {
		this.moduleName = moduleName;
	}

	@Column(name = "functionname")
	public String getfunctionName() {
		return this.functionName;
	}
	
	public void setfunctionName(String functionname) {
		this.functionName = functionname;
	}
	
	@Column(name = "message")
	public String getmessage() {
		return this.message;
	}

	public void setmessage(String message) {
		this.message = message;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss.SSS")
	@Column(name = "messagetime", length = 23)
	public Date getmessageTime() {
		return this.messageTime;
	}
	public void setmessageTime(Date messageTime) {
		this.messageTime = messageTime;
	}
	@JsonIgnore
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss.SSS")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastUpdated", length = 23)
	public Date getlastUpdated() {
		return this.lastUpdated;
	}
	public void setlastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}


}
