package com.APIMM.mam.model;
// Generated Sep 13, 2017 6:30:10 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * MamDevRouteHistorical generated by hbm2java
 */
@Entity
@Table(name = "MAM_Dev_Run_Historical")
public class MamDevRunHistorical implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer devRunID;	
	private MamDevRouteHistorical mamRoute;	
	private String runId;
	private String runDescription;
	private String runBeginPlan;
	private String runEndPlan;
	private Date devRunCreated;

	public MamDevRunHistorical() {
	}

	public MamDevRunHistorical(Integer devRunID, MamDevRouteHistorical MamrouteHistorical) {
		this.devRunID = devRunID;
		this.mamRoute = MamrouteHistorical;
	}

	public MamDevRunHistorical(Integer devRunID, MamDevRouteHistorical MamrouteHistorical, String runId, Date devRunCreated) {
		this.devRunID = devRunID;
		this.mamRoute = MamrouteHistorical;
		this.runId = runId;
		this.devRunCreated = devRunCreated;
	}
		

	@Id
	@JsonIgnore
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dev_run_id", unique = true, nullable = false, length = 1)
	public Integer getdevRunID() {
		return this.devRunID;
	}

	public void setdevRunID(Integer devRunID) {
		this.devRunID = devRunID;
	}
	@ManyToOne(cascade=CascadeType.MERGE, fetch=FetchType.EAGER)
	@JsonIgnore
	@JoinColumn(name = "dev_route_id", nullable = false )
	public MamDevRouteHistorical getmamRoute() {
		return this.mamRoute;
	}
	public void setmamRoute(MamDevRouteHistorical MamrouteHistorical) {
		this.mamRoute = MamrouteHistorical;
	}
	
	@Column(name = "run_id")
	public String getrunId() {
		return this.runId;
	}

	public void setrunId(String runId) {
		this.runId = runId;
	}
	
	@Column(name = "run_description")
	public String getrunDescription() {
		return this.runDescription;
	}

	public void setrunDescription(String runDescription) {
		this.runDescription = runDescription;
	}
	@Column(name = "run_beginplan")
	public String getrunBeginPlan() {
		return this.runBeginPlan;
	}

	public void setrunBeginPlan(String runBeginPlan) {
		this.runBeginPlan = runBeginPlan;
	}
	@Column(name = "run_endplan")
	public String getrunEndPlan() {
		return this.runEndPlan;
	}

	public void setrunEndPlan(String runEndPlan) {
		this.runEndPlan = runEndPlan;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
	@Column(name = "dev_run_created", length = 23)
	public Date getdevRunCreated() {
		return this.devRunCreated;
	}

	public void setdevRunCreated(Date devRunCreated) {
		this.devRunCreated = devRunCreated;
	}

}
