package com.APIMM.mam.model;
// Generated Nov 13, 2017 11:32:06 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MamEvents generated by hbm2java
 */
@Entity
@Table(name = "MAM_Events")
public class MamEvents implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer eventId;
	private String eventName;
	private String eventDescription;
	private Date eventUpdated;

	public MamEvents() {
	}

	public MamEvents(String eventName, String eventDescription, Date eventUpdated) {
		this.eventName = eventName;
		this.eventDescription = eventDescription;
		this.eventUpdated = eventUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "event_id", unique = true, nullable = false)
	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	@Column(name = "event_name")
	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	@Column(name = "event_description")
	public String getEventDescription() {
		return this.eventDescription;
	}

	public void setEventDescription(String eventDescription) {
		this.eventDescription = eventDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "event_updated", length = 23)
	public Date getEventUpdated() {
		return this.eventUpdated;
	}

	public void setEventUpdated(Date eventUpdated) {
		this.eventUpdated = eventUpdated;
	}

}
