package com.APIMM.mam.model;
// Generated Nov 13, 2017 11:32:06 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MamEvents generated by hbm2java
 */
@Entity
@Table(name = "MAM_Files")
public class MamFiles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer fileId;
	private String fileType;
	private String version;
	private String url;
	private Integer fileSize;
	private Date fileUpdate;

	public MamFiles() {
	}

	public MamFiles(String fileType, String version, String url, Date fileUpdate) {
		this.fileType = fileType;
		this.version = version;
		this.url = url;
		this.fileUpdate = fileUpdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "file_id", unique = true, nullable = false)
	public Integer getfileId() {
		return this.fileId;
	}

	public void setfileId(Integer fileId) {
		this.fileId = fileId;
	}

	@Column(name = "file_type")
	public String getfileType() {
		return this.fileType;
	}

	public void setfileType(String fileType) {
		this.fileType = fileType;
	}

	@Column(name = "file_version")
	public String getversion() {
		return this.version;
	}

	public void setversion(String version) {
		this.version = version;
	}
	@Column(name = "file_url")
	public String geturl() {
		return this.url;
	}

	public void seturl(String url) {
		this.url = url;
	}
	@Column(name = "filesize")
	public Integer getfileSize() {
		return this.fileSize;
	}

	public void setfileSize(Integer fileSize) {
		this.fileSize = fileSize;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "file_updated", length = 23)
	@JsonIgnore
	public Date getfileUpdate() {
		return this.fileUpdate;
	}

	public void setfileUpdate(Date fileUpdate) {
		this.fileUpdate = fileUpdate;
	}
}
