package com.APIMM.mam.model;
// Generated Sep 13, 2017 6:30:10 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MamModuleSetting generated by hbm2java
 */
@Entity
@Table(name = "MAM_Module_Setting")
public class MamModuleSetting implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer moduleSettingId;
	private MamModule mamModules;
	private MamSetting mamSettings;
	

	public MamModuleSetting() {
	}

	public MamModuleSetting(Integer moduleSettingId, MamModule mamModules, MamSetting mamSettings) {
		this.moduleSettingId = moduleSettingId;
		this.mamModules = mamModules;
		this.mamSettings = mamSettings;
	}
	

	@Id

	@Column(name = "module_setting_id", unique = true, nullable = false)
	public Integer getModuleSettingId() {
		return this.moduleSettingId;
	}

	public void setModuleSettingId(Integer moduleSettingId) {
		this.moduleSettingId = moduleSettingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module_id", nullable = false)
	public MamModule getMamModules() {
		return this.mamModules;
	}

	public void setMamModules(MamModule mamModules) {
		this.mamModules = mamModules;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "setting_id", nullable = false)
	public MamSetting getMamSettings() {
		return this.mamSettings;
	}

	public void setMamSettings(MamSetting mamSettings) {
		this.mamSettings = mamSettings;
	}	
	
	

}
