package com.APIMM.mam.model;
// Generated Nov 13, 2017 11:32:06 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MamSwipeEvent generated by hbm2java
 */
@Entity
public class MamSwipeEvent implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer deviceStuEventId;
	private Integer devId;
	private String busId;
	private Double latitude;
	private Double longitude;
	private Date eventTime;
	private Date eventSend;
	private Date eventWriteTime;
	private Integer eventId;
	private String eventName;
	private String studentId;
	private String studentName;
	private String status;	
	private String stopRunId;
	private String runId;
	private String runRoute;
	private String tagId;
	public MamSwipeEvent() {
	}
	public MamSwipeEvent(Integer devId, String busId, Double latitude, Double longitude, Date eventTime,
			Date eventSend, Date eventWriteTime, Integer eventId, String eventName, String studentId, String studentName, 
			String status, String stopRunId, String runId, String runRoute, String tagId) {
		this.devId = devId;
		this.busId = busId;
		this.latitude = latitude;
		this.longitude = longitude;
		this.eventTime = eventTime;
		this.eventSend = eventSend;
		this.eventWriteTime = eventWriteTime;
		this.eventId = eventId;
		this.eventName = eventName;
		this.studentId = studentId;
		this.studentName = studentName;		
		this.runId = runId;
		this.runRoute = runRoute;
		this.tagId = tagId;
	}	
	@Id
	@GeneratedValue(strategy = IDENTITY)	
	public Integer getdeviceStuEventId() {
		return this.deviceStuEventId;
	}

	public void setdeviceStuEventId(Integer deviceStuEventId) {
		this.deviceStuEventId = deviceStuEventId;
	}
	
	public Integer getDevId() {
		return this.devId;
	}

	public void setDevId(Integer devId) {
		this.devId = devId;
	}
	
	public String gettagId() {
		return this.tagId;
	}

	public void settagId(String tagId) {
		this.tagId = tagId;
	}
	
	public String getBusId() {
		return this.busId;
	}

	public void setBusId(String busId) {
		this.busId = busId;
	}
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}
	
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss.SSS")
	public Date getEventTime() {
		return this.eventTime;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss.SSS")	
	public Date getEventSend() {
		return this.eventSend;
	}

	public void setEventSend(Date eventSend) {
		this.eventSend = eventSend;
	}
	@Column(name = "event_write_tstamp",nullable= false)
	@Temporal(TemporalType.TIMESTAMP)	
	@JsonIgnore
	public Date geteventWriteTime() {		
		return eventWriteTime;
	}
	public void seteventWriteTime(Date eventWriteTime) {				
		this.eventWriteTime = eventWriteTime;
	}	
	
	@JsonIgnore
	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}
	
	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}	
	
	public String getstudentId() {
		return this.studentId;
	}

	public void setstudentId(String studentId) {
		this.studentId = studentId;
	}	
	
	public String getstudentName() {
		return this.studentName;
	}

	public void setstudentName(String studentName) {
		this.studentName = studentName;
	}	
	
	public String getstatus() {
		return this.status;
	}

	public void setstatus(String status) {
		this.status = status;
	}	
	
	public String getstopRunId() {
		return this.stopRunId;
	}

	public void setstopRunId(String stopRunId) {
		this.stopRunId = stopRunId;
	}
	public String getrunId() {
		return this.runId;
	}

	public void setrunId(String runId) {
		this.runId = runId;
	}	
	
	public String getrunRoute() {
		return this.runRoute;
	}

	public void setrunRoute(String runRoute) {
		this.runRoute = runRoute;
	}
}
