package com.APIMM.mam.model;
// Generated Sep 13, 2017 6:30:10 PM by Hibernate Tools 5.2.3.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MdmModes generated by hbm2java
 */
@Entity
@Table(name = "MDM_Modes")
public class MdmMode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer modeId;
	private String modeName;
	private String modeDescription;
	private Set<MdmDeviceMode> mdmDeviceModes = new HashSet<MdmDeviceMode>(0);

	public MdmMode() {
	}

	public MdmMode(Integer modeId) {
		this.modeId = modeId;
	}

	public MdmMode(Integer modeId, String modeName, String modeDescription,
			Set<MdmDeviceMode> mdmDeviceModes) {
		this.modeId = modeId;
		this.modeName = modeName;
		this.modeDescription = modeDescription;
		this.mdmDeviceModes = mdmDeviceModes;
	}

	@Id

	@Column(name = "mode_id", unique = true, nullable = false)
	public Integer getModeId() {
		return this.modeId;
	}

	public void setModeId(Integer modeId) {
		this.modeId = modeId;
	}

	@Column(name = "mode_name")
	public String getModeName() {
		return this.modeName;
	}

	public void setModeName(String modeName) {
		this.modeName = modeName;
	}

	@Column(name = "mode_description")
	public String getModeDescription() {
		return this.modeDescription;
	}

	public void setModeDescription(String modeDescription) {
		this.modeDescription = modeDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mdmModes")
	public Set<MdmDeviceMode> getMdmDeviceModes() {
		return this.mdmDeviceModes;
	}

	public void setMdmDeviceModes(Set<MdmDeviceMode> mdmDeviceModes) {
		this.mdmDeviceModes = mdmDeviceModes;
	}

}
