package com.APIMM.mam.model;
// Generated Nov 13, 2017 11:32:06 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MamDeviceEvent generated by hbm2java
 */
@Entity
public class RunDirs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;	
	private Integer id;
	private Integer devId;
	private String busNumber;
	private Integer sequence;
	private Date time;
	private Double latitude;
	private Double longitude;
	
	public RunDirs() {
	}

	public RunDirs( Integer id, Integer devId,String busNumber, Date time, Integer sequence, Double latitude,Double longitude) {
		super();	
		this.id=id;
		this.devId = devId;
		this.busNumber = busNumber;
		this.time = time;
		this.sequence = sequence;
		this.latitude = latitude;
		this.longitude = longitude;		
	}

	@Id
	@JsonIgnore
	@GeneratedValue(strategy = IDENTITY)
	
	public Integer getid() {
		return this.id;
	}
	public void setid(Integer id) {
		this.id = id;
	}   
	
	public Integer getdevId() {
		return this.devId;
	}

	public void setdevId(Integer devId) {
		this.devId = devId;
	}
	public String getbusNumber() {
		return this.busNumber;
	}

	public void setbusNumber(String busNumber) {
		this.busNumber = busNumber;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss.SSS")
	public Date gettime() {
		return this.time;
	}

	public void settime(Date time) {
		this.time = time;
	}
	public Integer getsequence() {
		return this.sequence;
	}

	public void setsequence(Integer sequence) {
		this.sequence = sequence;
	}
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}
	
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}		

}
