package com.ADP.name.model;
// Generated Sep 6, 2017 6:03:46 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * PrsMain generated by hbm2java
 */
@Entity
@Table(name = "PRS_MAIN")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String sysId;
	private Integer depId;
	private String prsId;
	private Character prsMidinit;
	private String prsFirstname;
	private String prsLastname;
	private String prsEmail;
	private String prsSsn;
	private Integer prsWrkgrp;
	private String prsWorkingloc;
	private String prsEmployer;
	private String prsUnion;
	private String prsSeniority;
	private String prsStatus;
	private Date prsHire;
	private Date prsTerminate;
	private String prsClass;
	private String prsGrade;
	private String prsLvl;
	private String prsPayType;
	private BigDecimal prsPayRate;
	private String prsRateFreq;
	private String prsPayFreq;
	private Date prsDob;
	private String prsSupervisor;
	private String prsPhone;
	private Date prsLastrvdate;
	private String prsLastrvperson;
	private Integer prsLastrvscore;
	private Date prsNextrvdate;
	private String prsNotes;
	private String prsImage;
	private String prsJobtittle;
	private String prsJobdesc;
	private String prsDistrict;
	private BigDecimal prsScaleHour;
	private String prsGroup;
	private Boolean isTempId;
	private String prsDualpostitle;
	private BigDecimal prsDualpospercent;
	private String prsDualposnote;
	private BigDecimal prsLeaverate;
	private Boolean prsBenefits;
	private String prsSchoolseqno;
	private String prsPassword;
	private Integer imageId;
	private Date prsPassexpdate;
	
	/*private List<Role> e_role;*/

	public User() {
	}

	public User(String sysId) {
		this.sysId = sysId;
	}

	public User(String sysId, Integer depId, String prsId, Character prsMidinit, String prsFirstname,
			String prsLastname, String prsEmail, String prsSsn, Integer prsWrkgrp, String prsWorkingloc,
			String prsEmployer, String prsUnion, String prsSeniority, String prsStatus, Date prsHire, Date prsTerminate,
			String prsClass, String prsGrade, String prsLvl, String prsPayType, BigDecimal prsPayRate,
			String prsRateFreq, String prsPayFreq, Date prsDob, String prsSupervisor, String prsPhone,
			Date prsLastrvdate, String prsLastrvperson, Integer prsLastrvscore, Date prsNextrvdate,
			String prsNotes, String prsImage, String prsJobtittle, String prsJobdesc,
			String prsDistrict, BigDecimal prsScaleHour, String prsGroup, Boolean isTempId, String prsDualpostitle,
			BigDecimal prsDualpospercent, String prsDualposnote, BigDecimal prsLeaverate, Boolean prsBenefits,
			String prsSchoolseqno, String prsPassword, Integer imageId, Date prsPassexpdate) {
		this.sysId = sysId;
		this.depId = depId;
		this.prsId = prsId;
		this.prsMidinit = prsMidinit;
		this.prsFirstname = prsFirstname;
		this.prsLastname = prsLastname;
		this.prsEmail = prsEmail;
		this.prsSsn = prsSsn;
		this.prsWrkgrp = prsWrkgrp;
		this.prsWorkingloc = prsWorkingloc;
		this.prsEmployer = prsEmployer;
		this.prsUnion = prsUnion;
		this.prsSeniority = prsSeniority;
		this.prsStatus = prsStatus;
		this.prsHire = prsHire;
		this.prsTerminate = prsTerminate;
		this.prsClass = prsClass;
		this.prsGrade = prsGrade;
		this.prsLvl = prsLvl;
		this.prsPayType = prsPayType;
		this.prsPayRate = prsPayRate;
		this.prsRateFreq = prsRateFreq;
		this.prsPayFreq = prsPayFreq;
		this.prsDob = prsDob;
		this.prsSupervisor = prsSupervisor;
		this.prsPhone = prsPhone;
		this.prsLastrvdate = prsLastrvdate;
		this.prsLastrvperson = prsLastrvperson;
		this.prsLastrvscore = prsLastrvscore;
		this.prsNextrvdate = prsNextrvdate;
		this.prsNotes = prsNotes;
		this.prsImage = prsImage;
		this.prsJobtittle = prsJobtittle;
		this.prsJobdesc = prsJobdesc;
		this.prsDistrict = prsDistrict;
		this.prsScaleHour = prsScaleHour;
		this.prsGroup = prsGroup;
		this.isTempId = isTempId;
		this.prsDualpostitle = prsDualpostitle;
		this.prsDualpospercent = prsDualpospercent;
		this.prsDualposnote = prsDualposnote;
		this.prsLeaverate = prsLeaverate;
		this.prsBenefits = prsBenefits;
		this.prsSchoolseqno = prsSchoolseqno;
		this.prsPassword = prsPassword;
		this.imageId = imageId;
		this.prsPassexpdate = prsPassexpdate;
	}

	@Id

	@Column(name = "SYS_ID", unique = true, nullable = false, length = 10)
	public String getSysId() {
		return this.sysId;
	}

	public void setSysId(String sysId) {
		this.sysId = sysId;
	}

	@Column(name = "DEP_ID")
	public Integer getDepId() {
		return this.depId;
	}

	public void setDepId(Integer depId) {
		this.depId = depId;
	}

	@Column(name = "PRS_ID", length = 20)
	public String getPrsId() {
		return this.prsId;
	}

	public void setPrsId(String prsId) {
		this.prsId = prsId;
	}

	@Column(name = "PRS_MIDINIT", length = 1)
	public Character getPrsMidinit() {
		return this.prsMidinit;
	}

	public void setPrsMidinit(Character prsMidinit) {
		this.prsMidinit = prsMidinit;
	}

	@Column(name = "PRS_FIRSTNAME", length = 25)
	public String getPrsFirstname() {
		return this.prsFirstname;
	}

	public void setPrsFirstname(String prsFirstname) {
		this.prsFirstname = prsFirstname;
	}

	@Column(name = "PRS_LASTNAME", length = 25)
	public String getPrsLastname() {
		return this.prsLastname;
	}

	public void setPrsLastname(String prsLastname) {
		this.prsLastname = prsLastname;
	}

	@Column(name = "PRS_EMAIL", length = 50)
	public String getPrsEmail() {
		return this.prsEmail;
	}

	public void setPrsEmail(String prsEmail) {
		this.prsEmail = prsEmail;
	}

	@Column(name = "PRS_SSN", length = 12)
	public String getPrsSsn() {
		return this.prsSsn;
	}

	public void setPrsSsn(String prsSsn) {
		this.prsSsn = prsSsn;
	}

	@Column(name = "PRS_WRKGRP")
	public Integer getPrsWrkgrp() {
		return this.prsWrkgrp;
	}

	public void setPrsWrkgrp(Integer prsWrkgrp) {
		this.prsWrkgrp = prsWrkgrp;
	}

	@Column(name = "PRS_WORKINGLOC", length = 12)
	public String getPrsWorkingloc() {
		return this.prsWorkingloc;
	}

	public void setPrsWorkingloc(String prsWorkingloc) {
		this.prsWorkingloc = prsWorkingloc;
	}

	@Column(name = "PRS_EMPLOYER", length = 15)
	public String getPrsEmployer() {
		return this.prsEmployer;
	}

	public void setPrsEmployer(String prsEmployer) {
		this.prsEmployer = prsEmployer;
	}

	@Column(name = "PRS_UNION", length = 30)
	public String getPrsUnion() {
		return this.prsUnion;
	}

	public void setPrsUnion(String prsUnion) {
		this.prsUnion = prsUnion;
	}

	@Column(name = "PRS_SENIORITY", length = 50)
	public String getPrsSeniority() {
		return this.prsSeniority;
	}

	public void setPrsSeniority(String prsSeniority) {
		this.prsSeniority = prsSeniority;
	}

	@Column(name = "PRS_STATUS", length = 10)
	public String getPrsStatus() {
		return this.prsStatus;
	}

	public void setPrsStatus(String prsStatus) {
		this.prsStatus = prsStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRS_HIRE", length = 23)
	public Date getPrsHire() {
		return this.prsHire;
	}

	public void setPrsHire(Date prsHire) {
		this.prsHire = prsHire;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRS_TERMINATE", length = 23)
	public Date getPrsTerminate() {
		return this.prsTerminate;
	}

	public void setPrsTerminate(Date prsTerminate) {
		this.prsTerminate = prsTerminate;
	}

	@Column(name = "PRS_CLASS", length = 15)
	public String getPrsClass() {
		return this.prsClass;
	}

	public void setPrsClass(String prsClass) {
		this.prsClass = prsClass;
	}

	@Column(name = "PRS_GRADE", length = 10)
	public String getPrsGrade() {
		return this.prsGrade;
	}

	public void setPrsGrade(String prsGrade) {
		this.prsGrade = prsGrade;
	}

	@Column(name = "PRS_LVL", length = 10)
	public String getPrsLvl() {
		return this.prsLvl;
	}

	public void setPrsLvl(String prsLvl) {
		this.prsLvl = prsLvl;
	}

	@Column(name = "PRS_PAY_TYPE", length = 10)
	public String getPrsPayType() {
		return this.prsPayType;
	}

	public void setPrsPayType(String prsPayType) {
		this.prsPayType = prsPayType;
	}

	@Column(name = "PRS_PAY_RATE", precision = 10, scale = 3)
	public BigDecimal getPrsPayRate() {
		return this.prsPayRate;
	}

	public void setPrsPayRate(BigDecimal prsPayRate) {
		this.prsPayRate = prsPayRate;
	}

	@Column(name = "PRS_RATE_FREQ", length = 10)
	public String getPrsRateFreq() {
		return this.prsRateFreq;
	}

	public void setPrsRateFreq(String prsRateFreq) {
		this.prsRateFreq = prsRateFreq;
	}

	@Column(name = "PRS_PAY_FREQ", length = 10)
	public String getPrsPayFreq() {
		return this.prsPayFreq;
	}

	public void setPrsPayFreq(String prsPayFreq) {
		this.prsPayFreq = prsPayFreq;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRS_DOB", length = 23)
	public Date getPrsDob() {
		return this.prsDob;
	}

	public void setPrsDob(Date prsDob) {
		this.prsDob = prsDob;
	}

	@Column(name = "PRS_SUPERVISOR", length = 25)
	public String getPrsSupervisor() {
		return this.prsSupervisor;
	}

	public void setPrsSupervisor(String prsSupervisor) {
		this.prsSupervisor = prsSupervisor;
	}

	@Column(name = "PRS_PHONE", length = 15)
	public String getPrsPhone() {
		return this.prsPhone;
	}

	public void setPrsPhone(String prsPhone) {
		this.prsPhone = prsPhone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRS_LASTRVDATE", length = 23)
	public Date getPrsLastrvdate() {
		return this.prsLastrvdate;
	}

	public void setPrsLastrvdate(Date prsLastrvdate) {
		this.prsLastrvdate = prsLastrvdate;
	}

	@Column(name = "PRS_LASTRVPERSON", length = 30)
	public String getPrsLastrvperson() {
		return this.prsLastrvperson;
	}

	public void setPrsLastrvperson(String prsLastrvperson) {
		this.prsLastrvperson = prsLastrvperson;
	}

	@Column(name = "PRS_LASTRVSCORE")
	public Integer getPrsLastrvscore() {
		return this.prsLastrvscore;
	}

	public void setPrsLastrvscore(Integer prsLastrvscore) {
		this.prsLastrvscore = prsLastrvscore;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRS_NEXTRVDATE", length = 23)
	public Date getPrsNextrvdate() {
		return this.prsNextrvdate;
	}

	public void setPrsNextrvdate(Date prsNextrvdate) {
		this.prsNextrvdate = prsNextrvdate;
	}

	@Column(name = "PRS_NOTES")
	public String getPrsNotes() {
		return this.prsNotes;
	}

	public void setPrsNotes(String prsNotes) {
		this.prsNotes = prsNotes;
	}

	@Column(name = "PRS_IMAGE")
	public String getPrsImage() {
		return this.prsImage;
	}

	public void setPrsImage(String prsImage) {
		this.prsImage = prsImage;
	}

	@Column(name = "PRS_JOBTITTLE", length = 25)
	public String getPrsJobtittle() {
		return this.prsJobtittle;
	}

	public void setPrsJobtittle(String prsJobtittle) {
		this.prsJobtittle = prsJobtittle;
	}

	@Column(name = "PRS_JOBDESC")
	public String getPrsJobdesc() {
		return this.prsJobdesc;
	}

	public void setPrsJobdesc(String prsJobdesc) {
		this.prsJobdesc = prsJobdesc;
	}

	@Column(name = "prs_district", length = 6)
	public String getPrsDistrict() {
		return this.prsDistrict;
	}

	public void setPrsDistrict(String prsDistrict) {
		this.prsDistrict = prsDistrict;
	}

	@Column(name = "prs_scale_hour", precision = 12, scale = 3)
	public BigDecimal getPrsScaleHour() {
		return this.prsScaleHour;
	}

	public void setPrsScaleHour(BigDecimal prsScaleHour) {
		this.prsScaleHour = prsScaleHour;
	}

	@Column(name = "prs_group", length = 30)
	public String getPrsGroup() {
		return this.prsGroup;
	}

	public void setPrsGroup(String prsGroup) {
		this.prsGroup = prsGroup;
	}

	@Column(name = "isTempID")
	public Boolean getIsTempId() {
		return this.isTempId;
	}

	public void setIsTempId(Boolean isTempId) {
		this.isTempId = isTempId;
	}

	@Column(name = "PRS_DUALPOSTITLE", length = 50)
	public String getPrsDualpostitle() {
		return this.prsDualpostitle;
	}

	public void setPrsDualpostitle(String prsDualpostitle) {
		this.prsDualpostitle = prsDualpostitle;
	}

	@Column(name = "PRS_DUALPOSPERCENT", precision = 4, scale = 1)
	public BigDecimal getPrsDualpospercent() {
		return this.prsDualpospercent;
	}

	public void setPrsDualpospercent(BigDecimal prsDualpospercent) {
		this.prsDualpospercent = prsDualpospercent;
	}

	@Column(name = "PRS_DUALPOSNOTE", length = 50)
	public String getPrsDualposnote() {
		return this.prsDualposnote;
	}

	public void setPrsDualposnote(String prsDualposnote) {
		this.prsDualposnote = prsDualposnote;
	}

	@Column(name = "PRS_LEAVERATE", precision = 5)
	public BigDecimal getPrsLeaverate() {
		return this.prsLeaverate;
	}

	public void setPrsLeaverate(BigDecimal prsLeaverate) {
		this.prsLeaverate = prsLeaverate;
	}

	@Column(name = "PRS_BENEFITS")
	public Boolean getPrsBenefits() {
		return this.prsBenefits;
	}

	public void setPrsBenefits(Boolean prsBenefits) {
		this.prsBenefits = prsBenefits;
	}

	@Column(name = "PRS_SCHOOLSEQNO", length = 12)
	public String getPrsSchoolseqno() {
		return this.prsSchoolseqno;
	}

	public void setPrsSchoolseqno(String prsSchoolseqno) {
		this.prsSchoolseqno = prsSchoolseqno;
	}

	@Column(name = "PRS_PASSWORD", length = 50)
	public String getPrsPassword() {
		return this.prsPassword;
	}

	public void setPrsPassword(String prsPassword) {
		this.prsPassword = prsPassword;
	}

	@Column(name = "ImageID")
	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRS_PASSEXPDATE", length = 23)
	public Date getPrsPassexpdate() {
		return this.prsPassexpdate;
	}

	public void setPrsPassexpdate(Date prsPassexpdate) {
		this.prsPassexpdate = prsPassexpdate;
	}
	
	/*@ManyToMany(cascade = CascadeType.MERGE, fetch = FetchType.EAGER)
	@JoinTable(name = "UserRole", joinColumns = {
			@JoinColumn(name = "UserID", nullable = false, updatable = false) },
			inverseJoinColumns = { @JoinColumn(name = "RoleID", nullable = false, updatable = false) })
	@JsonIgnoreProperties({"e_user"})*/
	/*public List<Role> getE_role() {
		return e_role;
	}
	public void setE_role(List<Role> e_role) {
		this.e_role = e_role;
	}*/	
}
