package com.APIMM.mam.nonemodel;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.APIMM.mam.model.MamModule;
import com.APIMM.mam.model.MdmDevice;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * MamDevModule generated by hbm2java
 */
@Entity
@Table(name = "MAM_Dev_Module")
public class NoneMamDevModule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer devModuleId;
	private MamModule mamModules;
	private MdmDevice mdmDevices;
	private String moduleName;
	private String moduleDescription;
	private Boolean devModuleEnable;
	private Boolean isDefault;
	private Date devModuleUpdated;
	private Integer devId;
	private Integer moduleId;

	public NoneMamDevModule() {
	}

	public NoneMamDevModule(Integer devModuleId, MamModule mamModules, MdmDevice mdmDevices) {
		this.devModuleId = devModuleId;
		this.mamModules = mamModules;
		this.mdmDevices = mdmDevices;
	}

	public NoneMamDevModule(Integer devModuleId, MamModule mamModules, MdmDevice mdmDevices, Boolean devModuleEnable,
			Boolean isDefault, Date devModuleUpdated) {
		this.devModuleId = devModuleId;
		this.mamModules = mamModules;
		this.mdmDevices = mdmDevices;
		this.devModuleEnable = devModuleEnable;
		this.isDefault = isDefault;
		this.devModuleUpdated = devModuleUpdated;

	}

	public Integer getDevModuleId() {
		return this.devModuleId;
	}

	public void setDevModuleId(Integer devModuleId) {
		this.devModuleId = devModuleId;
	}

	public Integer getDevId() {
		if (this.mdmDevices != null) {
			return this.mdmDevices.getdevID();
		}
		return null;
	}

	public void setDevId(Integer devId) {
		this.devId = devId;
	}

	public Integer getModuleId() {
		if (this.mamModules != null) {
			return this.mamModules.getModuleId();
		}
		return null;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	@JsonIgnore
	public MamModule getMamModules() {
		return this.mamModules;
	}

	public void setMamModules(MamModule mamModules) {
		this.mamModules = mamModules;
	}

	@JsonIgnore
	public MdmDevice getMdmDevices() {
		return this.mdmDevices;
	}

	public void setMdmDevices(MdmDevice mdmDevices) {
		this.mdmDevices = mdmDevices;
	}

	public Boolean getDevModuleEnable() {
		return this.devModuleEnable;
	}

	public void setDevModuleEnable(Boolean devModuleEnable) {
		this.devModuleEnable = devModuleEnable;
	}

	public Boolean getisDefault() {
		return this.isDefault;
	}

	public void setisDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}

	public Date getDevModuleUpdated() {
		return this.devModuleUpdated;
	}

	public void setDevModuleUpdated(Date devModuleUpdated) {
		this.devModuleUpdated = devModuleUpdated;
	}

	public String getmoduleName() {
		if (this.mamModules != null) {
			return this.mamModules.getModuleName();
		}
		return "";
	}

	public void setmoduleName(String modulename) {
		this.moduleName = modulename;
	}

	public String getmoduleDescription() {
		if (this.mamModules != null) {
			return this.mamModules.getModuleDescription();
		}
		return "";
	}

	public void setmoduleDescription(String moduledescription) {
		this.moduleDescription = moduledescription;
	}

}
