package com.APIMM.etgps.model;
// Generated Nov 14, 2017 1:55:59 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * BusPositionId generated by hbm2java
 */
@Entity
@Table(name = "BusPosition")
public class BusPosition implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer districtId;
	private String unitId;
	private Double latitude;
	private Double longitude;
	private Date writeTimeStamp;
	private Date positionTimeStamp;
	private Integer eventId;
	private Double speed;
	private Double rssi;
	private Double routeMiles;
	private Long id;
	private Long logId;

	public BusPosition() {
	}

	public BusPosition(long id) {
		this.id = id;
	}

	public BusPosition(Integer districtId, String unitId, Double latitude, Double longitude,
			Date writeTimeStamp, Date positionTimeStamp, Integer eventId, Double speed, Double rssi, Double routeMiles,
			long id, Long logId) {
		this.districtId = districtId;
		this.unitId = unitId;
		this.latitude = latitude;
		this.longitude = longitude;
		this.writeTimeStamp = writeTimeStamp;
		this.positionTimeStamp = positionTimeStamp;
		this.eventId = eventId;
		this.speed = speed;
		this.rssi = rssi;
		this.routeMiles = routeMiles;
		this.id = id;
		this.logId = logId;
	}

	@Column(name = "DistrictID")
	public Integer getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	@Column(name = "UnitID")
	public String getUnitId() {
		return this.unitId;
	}

	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}

	@Column(name = "Latitude", precision = 53, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "Longitude", precision = 53, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	//@Column(name = "WriteTimeStamp", length = 23)	
	@Column(name="WriteTimeStamp", length = 23)
	@Temporal(TemporalType.TIMESTAMP)
	
	public Date getWriteTimeStamp() {
		return this.writeTimeStamp;
	}

	public void setWriteTimeStamp(Date writeTimeStamp) {
		this.writeTimeStamp = writeTimeStamp;
	}

	@Column(name = "PositionTimeStamp", length = 23)
	public Date getPositionTimeStamp() {
		return this.positionTimeStamp;
	}

	public void setPositionTimeStamp(Date positionTimeStamp) {
		this.positionTimeStamp = positionTimeStamp;
	}

	@Column(name = "EventID")
	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	@Column(name = "Speed", precision = 53, scale = 0)
	public Double getSpeed() {
		return this.speed;
	}

	public void setSpeed(Double speed) {
		this.speed = speed;
	}

	@Column(name = "RSSI", precision = 53, scale = 0)
	public Double getRssi() {
		return this.rssi;
	}

	public void setRssi(Double rssi) {
		this.rssi = rssi;
	}

	@Column(name = "RouteMiles", precision = 53, scale = 0)
	public Double getRouteMiles() {
		return this.routeMiles;
	}

	public void setRouteMiles(Double routeMiles) {
		this.routeMiles = routeMiles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "LogID")
	public Long getLogId() {
		return this.logId;
	}

	public void setLogId(Long logId) {
		this.logId = logId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BusPosition))
			return false;
		BusPosition castOther = (BusPosition) other;

		return ((this.getDistrictId() == castOther.getDistrictId()) || (this.getDistrictId() != null
				&& castOther.getDistrictId() != null && this.getDistrictId().equals(castOther.getDistrictId())))
				&& ((this.getUnitId() == castOther.getUnitId()) || (this.getUnitId() != null
						&& castOther.getUnitId() != null && this.getUnitId().equals(castOther.getUnitId())))
				&& ((this.getLatitude() == castOther.getLatitude()) || (this.getLatitude() != null
						&& castOther.getLatitude() != null && this.getLatitude().equals(castOther.getLatitude())))
				&& ((this.getLongitude() == castOther.getLongitude()) || (this.getLongitude() != null
						&& castOther.getLongitude() != null && this.getLongitude().equals(castOther.getLongitude())))
				&& ((this.getWriteTimeStamp() == castOther.getWriteTimeStamp())
						|| (this.getWriteTimeStamp() != null && castOther.getWriteTimeStamp() != null
								&& this.getWriteTimeStamp().equals(castOther.getWriteTimeStamp())))
				&& ((this.getPositionTimeStamp() == castOther.getPositionTimeStamp())
						|| (this.getPositionTimeStamp() != null && castOther.getPositionTimeStamp() != null
								&& this.getPositionTimeStamp().equals(castOther.getPositionTimeStamp())))
				&& ((this.getEventId() == castOther.getEventId()) || (this.getEventId() != null
						&& castOther.getEventId() != null && this.getEventId().equals(castOther.getEventId())))
				&& ((this.getSpeed() == castOther.getSpeed()) || (this.getSpeed() != null
						&& castOther.getSpeed() != null && this.getSpeed().equals(castOther.getSpeed())))
				&& ((this.getRssi() == castOther.getRssi()) || (this.getRssi() != null && castOther.getRssi() != null
						&& this.getRssi().equals(castOther.getRssi())))
				&& ((this.getRouteMiles() == castOther.getRouteMiles()) || (this.getRouteMiles() != null
						&& castOther.getRouteMiles() != null && this.getRouteMiles().equals(castOther.getRouteMiles())))
				&& (this.getId() == castOther.getId())
				&& ((this.getLogId() == castOther.getLogId()) || (this.getLogId() != null
						&& castOther.getLogId() != null && this.getLogId().equals(castOther.getLogId())));
	}
}
