package com.APIMM.etgps.model;
// Generated Nov 14, 2017 1:55:59 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BusPositionId generated by hbm2java
 */
@Entity
@Table(name = "Message")
public class Message implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long messageId;
	private Date messageDateReceived;
	private Date messageDateEvent;
	private Integer messageEventId;
	private String messageVehicleId;
	private Double latitude;
	private Double longitude;
	private String messageComment;
	private Date messageDateAdjusted;
	public Message() {
	}

	public Message(long id) {
		this.messageId = id;
	}

	public Message(Integer messageEventId, String messageVehicleId, Double latitude, Double longitude,
			Date messageDateReceived, Date messageDateEvent, long messageId, String messageComment, Date messageDateAdjusted) {
		this.messageEventId = messageEventId;
		this.messageVehicleId = messageVehicleId;
		this.latitude = latitude;
		this.longitude = longitude;
		this.messageDateReceived = messageDateReceived;
		this.messageDateEvent = messageDateEvent;
		this.messageId = messageId;		
		this.messageComment = messageComment;
		this.messageDateAdjusted = messageDateAdjusted;
	}

	@Column(name = "message_event_id")
	public Integer getmessageEventId() {
		return this.messageEventId;
	}

	public void setmessageEventId(Integer messageEventId) {
		this.messageEventId = messageEventId;
	}

	@Column(name = "message_vehicle_id")
	public String getmessageVehicleId() {
		return this.messageVehicleId;
	}

	public void setmessageVehicleId(String messageVehicleId) {
		this.messageVehicleId = messageVehicleId;
	}

	@Column(name = "message_latitude", precision = 53, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "message_longitude", precision = 53, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "message_dt_received", length = 23)
	public Date getmessageDateReceived() {
		return this.messageDateReceived;
	}

	public void setmessageDateReceived(Date messageDateReceived) {
		this.messageDateReceived = messageDateReceived;
	}

	@Column(name = "message_dt_event", length = 23)
	public Date getmessageDateEvent() {
		return this.messageDateEvent;
	}

	public void setmessageDateEvent(Date messageDateEvent) {
		this.messageDateEvent = messageDateEvent;
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "message_id", nullable = false)
	public Long getmessageId() {
		return this.messageId;
	}

	public void setmessageId(Long id) {
		this.messageId = id;
	}

	@Column(name = "message_comment")
	public String getmessageComment() {
		return this.messageComment;
	}

	public void setmessageComment(String messageComment) {
		this.messageComment = messageComment;
	}
	@Column(name = "message_dt_adjusted", length = 23)
	public Date getmessageDateAdjusted() {
		return this.messageDateAdjusted;
	}

	public void setmessageDateAdjusted(Date messageDateAdjusted) {
		this.messageDateAdjusted = messageDateAdjusted;
	}
}
