package com.APIMM.etgps.model;
// Generated Nov 14, 2017 1:55:59 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StudentId generated by hbm2java
 */
@Embeddable
public class StudentId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String studentId;
	private String status;
	private Double latitude;
	private Double longitude;
	private Date writeTimeStamp;
	private Date positionTimeStamp;
	private String unitId;

	public StudentId() {
	}

	public StudentId(String studentId, String status, Double latitude, Double longitude, Date writeTimeStamp,
			Date positionTimeStamp, String unitId) {
		this.studentId = studentId;
		this.status = status;
		this.latitude = latitude;
		this.longitude = longitude;
		this.writeTimeStamp = writeTimeStamp;
		this.positionTimeStamp = positionTimeStamp;
		this.unitId = unitId;
	}

	@Column(name = "StudentID", length = 50)
	public String getStudentId() {
		return this.studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	@Column(name = "Status", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "Latitude", precision = 53, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "Longitude", precision = 53, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "WriteTimeStamp", length = 23)
	public Date getWriteTimeStamp() {
		return this.writeTimeStamp;
	}

	public void setWriteTimeStamp(Date writeTimeStamp) {
		this.writeTimeStamp = writeTimeStamp;
	}

	@Column(name = "PositionTimeStamp", length = 23)
	public Date getPositionTimeStamp() {
		return this.positionTimeStamp;
	}

	public void setPositionTimeStamp(Date positionTimeStamp) {
		this.positionTimeStamp = positionTimeStamp;
	}

	@Column(name = "UnitID")
	public String getUnitId() {
		return this.unitId;
	}

	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentId))
			return false;
		StudentId castOther = (StudentId) other;

		return ((this.getStudentId() == castOther.getStudentId()) || (this.getStudentId() != null
				&& castOther.getStudentId() != null && this.getStudentId().equals(castOther.getStudentId())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getLatitude() == castOther.getLatitude()) || (this.getLatitude() != null
						&& castOther.getLatitude() != null && this.getLatitude().equals(castOther.getLatitude())))
				&& ((this.getLongitude() == castOther.getLongitude()) || (this.getLongitude() != null
						&& castOther.getLongitude() != null && this.getLongitude().equals(castOther.getLongitude())))
				&& ((this.getWriteTimeStamp() == castOther.getWriteTimeStamp())
						|| (this.getWriteTimeStamp() != null && castOther.getWriteTimeStamp() != null
								&& this.getWriteTimeStamp().equals(castOther.getWriteTimeStamp())))
				&& ((this.getPositionTimeStamp() == castOther.getPositionTimeStamp())
						|| (this.getPositionTimeStamp() != null && castOther.getPositionTimeStamp() != null
								&& this.getPositionTimeStamp().equals(castOther.getPositionTimeStamp())))
				&& ((this.getUnitId() == castOther.getUnitId()) || (this.getUnitId() != null
						&& castOther.getUnitId() != null && this.getUnitId().equals(castOther.getUnitId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStudentId() == null ? 0 : this.getStudentId().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getLatitude() == null ? 0 : this.getLatitude().hashCode());
		result = 37 * result + (getLongitude() == null ? 0 : this.getLongitude().hashCode());
		result = 37 * result + (getWriteTimeStamp() == null ? 0 : this.getWriteTimeStamp().hashCode());
		result = 37 * result + (getPositionTimeStamp() == null ? 0 : this.getPositionTimeStamp().hashCode());
		result = 37 * result + (getUnitId() == null ? 0 : this.getUnitId().hashCode());
		return result;
	}

}
