package com.APIMM.etgps.model;
// Generated Nov 14, 2017 1:55:59 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UnknownStudent generated by hbm2java
 */
@Entity
@Table(name = "UnknownStudent")
public class UnknownStudent implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer unknownId;
	private String unitId;
	private String studentName;
	private Double longitude;
	private Double latitude;
	private Date positionTimeStamp;
	private String source;

	public UnknownStudent() {
	}

	public UnknownStudent(String unitId, String studentName, Double longitude, Double latitude, Date positionTimeStamp,
			String source) {
		this.unitId = unitId;
		this.studentName = studentName;
		this.longitude = longitude;
		this.latitude = latitude;
		this.positionTimeStamp = positionTimeStamp;
		this.source = source;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UnknownID", unique = true, nullable = false)
	public Integer getUnknownId() {
		return this.unknownId;
	}

	public void setUnknownId(Integer unknownId) {
		this.unknownId = unknownId;
	}

	@Column(name = "UnitID", length = 50)
	public String getUnitId() {
		return this.unitId;
	}

	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}

	@Column(name = "StudentName", length = 50)
	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	@Column(name = "Longitude", precision = 53, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "Latitude", precision = 53, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PositionTimeStamp", length = 23)
	public Date getPositionTimeStamp() {
		return this.positionTimeStamp;
	}

	public void setPositionTimeStamp(Date positionTimeStamp) {
		this.positionTimeStamp = positionTimeStamp;
	}

	@Column(name = "Source", length = 50)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

}
